name: Integration Tests

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  push:
    branches: 
      - 'main'
      - 'develop'
      - 'release/*'

jobs:
    integration-tests:
        runs-on: [macos-13]
    
        defaults:
          run:
            shell: zsh {0}

        concurrency: 
          group: integration-tests-${{ github.ref }}
          cancel-in-progress: true

        env:
          XCODE_VERSION_PATH: /Applications/Xcode_14.3.1.app
          TEST_DESTINATION: platform=iOS Simulator,name=iPhone 14,OS=latest
          INTEGRATION_TESTS_RESULTS_PATH: /tmp/UITestingSampleApp.xcresult

        steps:
            - name: Checkout
              uses: actions/checkout@v4
  
            - name: Setup Xcode version
              run: sudo xcode-select -s ${{ env.XCODE_VERSION_PATH }}

            - name: Run integration tests
              working-directory: Tests/IntegrationTests/UITestingSampleApp
              run: xcrun xcodebuild -scheme UITestingSampleApp clean test -testPlan UITestingSampleApp -destination "${{ env.TEST_DESTINATION }}" -resultBundlePath "${{ env.INTEGRATION_TESTS_RESULTS_PATH }}" -quiet